//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TVSGamingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TVSGamingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVS.Common.Resources.TVSGamingResources", typeof(TVSGamingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessToken in header does not match with the existing Token in Database against the userid.
        /// </summary>
        internal static string AccessTokenNotMatch {
            get {
                return ResourceManager.GetString("AccessTokenNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadRequest.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel_Stats File missing.
        /// </summary>
        internal static string BadRequestFileMissing {
            get {
                return ResourceManager.GetString("BadRequestFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid VehicleTypeID.
        /// </summary>
        internal static string BadRequestInvalidVehicleTypeID {
            get {
                return ResourceManager.GetString("BadRequestInvalidVehicleTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeTypeId missing.
        /// </summary>
        internal static string BadRequestModeTypeIdMissing {
            get {
                return ResourceManager.GetString("BadRequestModeTypeIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform missing.
        /// </summary>
        internal static string BadRequestPlatformMissing {
            get {
                return ResourceManager.GetString("BadRequestPlatformMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKey invalid.
        /// </summary>
        internal static string BadRequestPublicKeyInvalid {
            get {
                return ResourceManager.GetString("BadRequestPublicKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicKey missing.
        /// </summary>
        internal static string BadRequestPublicKeyMissing {
            get {
                return ResourceManager.GetString("BadRequestPublicKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to travelFileName missing.
        /// </summary>
        internal static string BadRequestTravelFileNameMissing {
            get {
                return ResourceManager.GetString("BadRequestTravelFileNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TravelId missing.
        /// </summary>
        internal static string BadRequestTravelIdMissing {
            get {
                return ResourceManager.GetString("BadRequestTravelIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAddressId missing.
        /// </summary>
        internal static string BadRequestUserAddressIdMissing {
            get {
                return ResourceManager.GetString("BadRequestUserAddressIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 5 records are not allowed, please remove the extra records.
        /// </summary>
        internal static string BadRequestUserAddressMaxLimit {
            get {
                return ResourceManager.GetString("BadRequestUserAddressMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId missing.
        /// </summary>
        internal static string BadRequestUserIdMissing {
            get {
                return ResourceManager.GetString("BadRequestUserIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserVehicleId missing.
        /// </summary>
        internal static string BadRequestUVIdMissing {
            get {
                return ResourceManager.GetString("BadRequestUVIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleTypeId missing.
        /// </summary>
        internal static string BadRequestVehicleTypeIdMissing {
            get {
                return ResourceManager.GetString("BadRequestVehicleTypeIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WidgetId missing.
        /// </summary>
        internal static string BadRequestWidgetIdMissing {
            get {
                return ResourceManager.GetString("BadRequestWidgetIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our &lt;b&gt; &lt;a href=&apos;com.tvsm.connect.help.TermsActivity://?type=terms&apos;&gt;Terms &amp;amp; Conditions&lt;/a&gt; &lt;/b&gt;have been updated please read and accept the Terms &amp;amp; Conditions to use your TVS Connect App..
        /// </summary>
        internal static string ConsentBody {
            get {
                return ResourceManager.GetString("ConsentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention!.
        /// </summary>
        internal static string ConsentHeader {
            get {
                return ResourceManager.GetString("ConsentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while accessing data from Database.
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving data in Database.
        /// </summary>
        internal static string DbSaveError {
            get {
                return ResourceManager.GetString("DbSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId in JSON body is not exact match with the header UserId.
        /// </summary>
        internal static string DifferentUserId {
            get {
                return ResourceManager.GetString("DifferentUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Fields Found..
        /// </summary>
        internal static string EmptyFieldsFound {
            get {
                return ResourceManager.GetString("EmptyFieldsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token is expired.
        /// </summary>
        internal static string ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field list.
        /// </summary>
        internal static string FieldList {
            get {
                return ResourceManager.GetString("FieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Forbidden.
        /// </summary>
        internal static string ForbiddenError {
            get {
                return ResourceManager.GetString("ForbiddenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string ForbiddenErrorRP {
            get {
                return ResourceManager.GetString("ForbiddenErrorRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game category code is required.
        /// </summary>
        internal static string GameCategoryCodeRequired {
            get {
                return ResourceManager.GetString("GameCategoryCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode is required.
        /// </summary>
        internal static string GameModeRequired {
            get {
                return ResourceManager.GetString("GameModeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game points are required.
        /// </summary>
        internal static string GamePointsRequired {
            get {
                return ResourceManager.GetString("GamePointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessToken is in-valid.
        /// </summary>
        internal static string InvalidAccessToken {
            get {
                return ResourceManager.GetString("InvalidAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments-.
        /// </summary>
        internal static string InvalidArgs {
            get {
                return ResourceManager.GetString("InvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid blood group.
        /// </summary>
        internal static string InvalidBloodGroup {
            get {
                return ResourceManager.GetString("InvalidBloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Refersh Token.
        /// </summary>
        internal static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsrId in Querystring parameter is not valid.
        /// </summary>
        internal static string InvalidUserIdInQueryString {
            get {
                return ResourceManager.GetString("InvalidUserIdInQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemNotFound.
        /// </summary>
        internal static string ItemNotFoundRP {
            get {
                return ResourceManager.GetString("ItemNotFoundRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token or Access token is missing.
        /// </summary>
        internal static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId or AccessToken is missing in HEADER.
        /// </summary>
        internal static string MissingUserId {
            get {
                return ResourceManager.GetString("MissingUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number is required.
        /// </summary>
        internal static string PageNumberRequired {
            get {
                return ResourceManager.GetString("PageNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size is required.
        /// </summary>
        internal static string PageSizeRequired {
            get {
                return ResourceManager.GetString("PageSizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing input params.
        /// </summary>
        internal static string ParamParseError {
            get {
                return ResourceManager.GetString("ParamParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordAlreadyAdded.
        /// </summary>
        internal static string RecordAlreadyAdded {
            get {
                return ResourceManager.GetString("RecordAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully.
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record added successfully.
        /// </summary>
        internal static string RecordSucessMessage {
            get {
                return ResourceManager.GetString("RecordSucessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully.
        /// </summary>
        internal static string RecordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("RecordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token and Access token are not of same user.
        /// </summary>
        internal static string RefreshNAccessTokenDifferent {
            get {
                return ResourceManager.GetString("RefreshNAccessTokenDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token in header does not match with the existing Token in Database against the userid.
        /// </summary>
        internal static string RefreshTokenNotMatch {
            get {
                return ResourceManager.GetString("RefreshTokenNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving file..
        /// </summary>
        internal static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
